### ISSUE TITLE
mac环境下安装出现编码错误

### ISSUE THREAD

**Issue by murray-sky** [depycode/burpsuite_hack#1]
SyntaxError: Non-ASCII character in file 'xxxx/burpsuite_hack/burpclient/BurpExtender_ALL.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

	at org.python.core.Py.SyntaxError(Py.java:171)
	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:105)
	at org.python.core.ParserFacade.parse(ParserFacade.java:190)
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/80733736/221736291-b984f1a9-f6d8-4cf3-bec4-8e87b66b0aa3.png">

**Comment by jan-call** [comment]
同款问题

**Comment by H3ll0W0lrd** [comment]
我这改完编码问题又出新了的问题。

![image](https://user-images.githubusercontent.com/30374511/221743099-0a9fd591-7a97-4100-92fa-b4f108add97d.png)

```
java.lang.ClassCastException: class org.python.core.PySingleton cannot be cast to class burp.IBurpExtender (org.python.core.PySingleton is in unnamed module of loader burp.mt2 @57669a49; burp.IBurpExtender is in unnamed module of loader 'app')
	at burp.nxn.e(Unknown Source)
	at burp.pf_.T(Unknown Source)
	at burp.m7e.l(Unknown Source)
	at burp.nv3.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by depycode** [comment]
参考这个：https://github.com/vmware/burp-rest-api/issues/6
这个错误不太清楚

**Comment by H3ll0W0lrd** [comment]
> 参考这个：[vmware/burp-rest-api#6](https://github.com/vmware/burp-rest-api/issues/6) 这个错误不太清楚

可能是版本问题，我MacOS上用的低版本的没有这个问题

**Comment by depycode** [comment]
我这边burpsuite  V2020、V2022 版本能正常加载

**Comment by murray-sky** [comment]
现在我的也可以了

**Comment by H3ll0W0lrd** [comment]
> 我这边burpsuite V2020、V2022 版本能正常加载

那这就无解了
