### ISSUE TITLE
ssrf问题

### ISSUE THREAD

**Issue by 1626947550** [depycode/burpsuite_hack#30]
Traceback (most recent call last):
  File "E:\Penetration\ProgramTools\Python3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Penetration\ProgramTools\Python3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "MyUDPHandler_Threads.py", line 117, in worker
    scan_vul(data)
  File "MyUDPHandler_Threads.py", line 130, in scan_vul
    ssrf = SSRF(http)
  File "E:\Penetration\TrafficTools\BurpSuite\plugins\BurpSuite-Plugin\Extender-plugin\burpsuite_hack\lib\plugins\ssrf.py", line 18, in __init__
    self.db = DBUtil()
  File "E:\Penetration\TrafficTools\BurpSuite\plugins\BurpSuite-Plugin\Extender-plugin\burpsuite_hack\lib\utils\DBUtil.py", line 15, in __init__
    self.port = int(Config.get_instance().get('mysql.PORT'))
ValueError: invalid literal for int() with base 10: '{port}'

**Comment by depycode** [comment]
配置文件改下
