### ISSUE TITLE
python MyUDPHandler_Threads.py之后报错  能不能工具使用简单点阿大佬

### ISSUE THREAD

**Issue by chenchen123423** [depycode/burpsuite_hack#40]
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "D:\DownLoad\burpsuite_hack-master\burpsuite_hack-master\MyUDPHandler_Threads.py", line 117, in worker
    scan_vul(data)
  File "D:\DownLoad\burpsuite_hack-master\burpsuite_hack-master\MyUDPHandler_Threads.py", line 130, in scan_vul
    ssrf = SSRF(http)
           ^^^^^^^^^^
  File "D:\DownLoad\burpsuite_hack-master\burpsuite_hack-master\lib\plugins\ssrf.py", line 18, in __init__
    self.db = DBUtil()
              ^^^^^^^^
  File "D:\DownLoad\burpsuite_hack-master\burpsuite_hack-master\lib\utils\DBUtil.py", line 15, in __init__
    self.port = int(Config.get_instance().get('mysql.PORT'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by chenchen123423** [comment]
数据库不会配置

**Comment by lizhianyuguangming** [comment]
burpsuite_hack-master\resources\app.config 这里面配置去掉{}
